[2025-06-21T08:43:36.626+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-21T08:43:36.640+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: twitter_etl_dag.extract_tweets scheduled__2025-06-20T00:00:00+00:00 [queued]>
[2025-06-21T08:43:36.644+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: twitter_etl_dag.extract_tweets scheduled__2025-06-20T00:00:00+00:00 [queued]>
[2025-06-21T08:43:36.644+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 6
[2025-06-21T08:43:36.649+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_tweets> on 2025-06-20 00:00:00+00:00
[2025-06-21T08:43:36.653+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl_dag', 'extract_tweets', 'scheduled__2025-06-20T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/twitter_etl_dag.py', '--cfg-path', '/tmp/tmp2p_3lkv4']
[2025-06-21T08:43:36.656+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask extract_tweets
[2025-06-21T08:43:36.656+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=186) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-21T08:43:36.658+0000] {standard_task_runner.py:63} INFO - Started process 187 to run task
[2025-06-21T08:43:36.682+0000] {task_command.py:426} INFO - Running <TaskInstance: twitter_etl_dag.extract_tweets scheduled__2025-06-20T00:00:00+00:00 [running]> on host 79810ee6c4d8
[2025-06-21T08:43:36.725+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='twitter_etl_dag' AIRFLOW_CTX_TASK_ID='extract_tweets' AIRFLOW_CTX_EXECUTION_DATE='2025-06-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-20T00:00:00+00:00'
[2025-06-21T08:43:36.726+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-21T08:43:37.355+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-21T08:43:37.356+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/twitter_etl_dag.py", line 44, in extract_tweets
    ti.xcom_push(key='raw_response', value=[tweet.to_dict() for tweet in tweets_data])
                                            ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tweepy/mixins.py", line 35, in __getattr__
    raise AttributeError from None
AttributeError
[2025-06-21T08:43:37.364+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_etl_dag, task_id=extract_tweets, run_id=scheduled__2025-06-20T00:00:00+00:00, execution_date=20250620T000000, start_date=20250621T084336, end_date=20250621T084337
[2025-06-21T08:43:37.373+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task extract_tweets (; 187)
[2025-06-21T08:43:37.383+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-21T08:43:37.396+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-21T08:43:37.397+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
